name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.1', '8.2', '8.3' ]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - name: Install dependencies
        run: composer install --no-interaction --no-progress
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit -c phpunit.xml.dist --testdox
      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse -c phpstan.neon.dist
